store in the local

diff --git a/Dockerfile.janus b/Dockerfile.janus
--- a/Dockerfile.janus
+++ b/Dockerfile.janus
@@ -57,10 +57,12 @@ RUN git clone https://github.com/meetecho/janus-gateway.git /opt/janus && \
     ./configure --enable-websockets --enable-data-channels --disable-rabbitmq --disable-mqtt --disable-docs && \
     make && make install && make configs
 
-# Copy Janus headers and usrsctp.h to /usr/local/include
+# Copy specified Janus headers to /usr/local/include
 RUN for file in loggers/logger.h plugins/plugin.h debug.h refcount.h apierror.h sdp-utils.h log.h rtcp.h mutex.h config.h rtpsrtp.h events/eventhandler.h transports/transport.h rtp.h text2pcap.h utils.h record.h ip-utils.h; do \
         cp /usr/local/include/janus/$file /usr/local/include/; \
-    done && cp /usr/local/include/usrsctp.h /usr/local/include/
+    done && \
+    [ -f /usr/local/include/usrsctp.h ] && cp /usr/local/include/usrsctp.h /usr/local/include/ || echo "usrsctp.h not found"
+
 
 # Verify that the headers are copied
 RUN ls /usr/local/include/*
